services:
  - type: web
    name: mediscopeai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn webapp.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        value: 10000
